#!/bin/sh
#/etc/init.d/cmdport

### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export HOME={home}

case "$1" in
  start)
  exec forever --sourceDir={installpath} -p {home}/.forever app.js
  ;;
stop)
  exec forever stop --sourceDir={installpath} app.js
  ;;
*)
  echo "Usage: /etc/init.d/cmdport {start|stop}"
  exit 1
  ;;
esac

exit 0
